# from flask_wtf import FlaskForm
# from wtforms import StringField, PasswordField, DecimalField
# from wtforms.validators import DataRequired    
# class EmailPasswordForm(FlaskForm):
#     in_ft1min=DecimalField('Min:', default = median_cut[0][0], validators=[DataRequired()])
#     in_ft1max=DecimalField('Max:', default = median_cut[0][1], validators=[DataRequired()])
    # in_ft2min=DecimalField('Min:', default = median_cut[1][0], validators=[DataRequired()])
    # in_ft2max=DecimalField('Max:', default = median_cut[1][1], validators=[DataRequired()])
    # in_ft3min=DecimalField('Min:', default = median_cut[2][0], validators=[DataRequired()])
    # in_ft3max=DecimalField('Max:', default = median_cut[2][1], validators=[DataRequired()])
    # in_ft4min=DecimalField('Min:', default = median_cut[3][0], validators=[DataRequired()])
    # in_ft4max=DecimalField('Max:', default = median_cut[3][1], validators=[DataRequired()])
    # in_ft5min=DecimalField('Min:', default = median_cut[4][0], validators=[DataRequired()])
    # in_ft5max=DecimalField('Max:', default = median_cut[4][1], validators=[DataRequired()])
    # in_ft6min=DecimalField('Min:', default = median_cut[5][0], validators=[DataRequired()])
    # in_ft6max=DecimalField('Max:', default = median_cut[5][1], validators=[DataRequired()])
    # in_ft7min=DecimalField('Min:', default = median_cut[6][0], validators=[DataRequired()])
    # in_ft7max=DecimalField('Max:', default = median_cut[6][1], validators=[DataRequired()])
    # in_ft8min=DecimalField('Min:', default = median_cut[7][0], validators=[DataRequired()])
    # in_ft8max=DecimalField('Max:', default = median_cut[7][1], validators=[DataRequired()])
    # in_ft9min=DecimalField('Min:', default = median_cut[8][0], validators=[DataRequired()])
    # in_ft9max=DecimalField('Max:', default = median_cut[8][1], validators=[DataRequired()])
    # in_ft10min=DecimalField('Min:', default = median_cut[9][0], validators=[DataRequired()])
    # in_ft10max=DecimalField('Max:', default = median_cut[9][1], validators=[DataRequired()])
    # in_ft11min=DecimalField('Min:', default = median_cut[10][0], validators=[DataRequired()])
    # in_ft11max=DecimalField('Max:', default = median_cut[10][1], validators=[DataRequired()])
    # in_ft12min=DecimalField('Min:', default = median_cut[11][0], validators=[DataRequired()])
    # in_ft12max=DecimalField('Max:', default = median_cut[11][1], validators=[DataRequired()])
    # in_ft13min=DecimalField('Min:', default = median_cut[12][0], validators=[DataRequired()])
    # in_ft13max=DecimalField('Max:', default = median_cut[12][1], validators=[DataRequired()])
    # in_ft14min=DecimalField('Min:', default = median_cut[13][0], validators=[DataRequired()])
    # in_ft14max=DecimalField('Max:', default = median_cut[13][1], validators=[DataRequired()])

    # form = EmailPasswordForm()
